name: Sypalo.com
url: https://sypalo.com
type: website
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      show: "true"
      type: "website"
  -
    scope:
      path: "content/en"
    values:
      lang: "en"
  -
    scope:
      path: "content/ru"      
    values:
      lang: "ru"
  -
    scope:
      path: "content/en/investing/articles"        
    values:      
      type: "article"
      comments: "true"
  -
    scope:
      path: "content/ru/инвестирование/статьи"
    values:      
      type: "article"
      comments: "true"
  -
    scope:
      path: "content/en/devops/articles"        
    values:      
      type: "article"
      comments: "true"
      affiliate: "affiliate-banners-650x1200-en-v3.jpg"
  -
    scope:
      path: "content/ru/девопс/статьи"
    values:      
      type: "article"
      comments: "true"
  -
    scope:
      path: "content/en/photo/articles"        
    values:      
      type: "article"
      comments: "true"
  -
    scope:
      path: "content/ru/фото/статьи"
    values:      
      type: "article"
      comments: "true"
  -
    scope:
      path: "content/en/movies/articles"
    values:      
      type: "article"
      comments: "true"
  -
    scope:
      path: "content/ru/фильмы/статьи"
    values:      
      type: "article"
      comments: "true"  