name: Sypalo.com
url: https://sypalo.com
type: website
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      show: "true"
      type: "website"
  -
    scope:
      path: "content/en"
    values:
      lang: "en"
  -
    scope:
      path: "content/ru"      
    values:
      lang: "ru"
  -
    scope:
      path: "content/en/investing/articles"        
    values:      
      type: "article"
      comments: "true"
      affiliate:
        link: "https://partners.etoro.com/B12184_A83946_TClick.aspx"
        banner: "etoro-banner.gif"
        text: "eToro banner"
  -
    scope:
      path: "content/ru/инвестирование/статьи"
    values:      
      type: "article"
      comments: "true"
  -
    scope:
      path: "content/en/devops/articles"        
    values:      
      type: "article"
      comments: "true"
      affiliate:
        link: "https://go.nordvpn.net/aff_c?offer_id=15&aff_id=42754&url_id=902"
        banner: "affiliate-banners-650x1200-en-v3.jpg"
        text: "NordVPN banner"
  -
    scope:
      path: "content/ru/девопс/статьи"
    values:      
      type: "article"
      comments: "true"
      affiliate:
          link: "https://go.nordvpn.net/aff_c?offer_id=15&aff_id=42754&url_id=902"
          banner: "affiliate-banners-650x1200-en-v3.jpg"
          text: "NordVPN баннер"
  -
    scope:
      path: "content/en/photo/articles"        
    values:      
      type: "article"
      comments: "true"
      affiliate:
          link: "https://www.jdoqocy.com/click-100158048-13228405"
          banner: "movavi.jpg"
          text: "Movavi - universal photo and video editor"
  -
    scope:
      path: "content/ru/фото/статьи"
    values:      
      type: "article"
      comments: "true"
      affiliate:
          link: "https://www.jdoqocy.com/click-100158048-13228405"
          banner: "movavi.jpg"
          text: "Movavi - универсальный фото-видео редактор"
  -
    scope:
      path: "content/en/movies/articles"
    values:      
      type: "article"
      comments: "true"
  -
    scope:
      path: "content/ru/фильмы/статьи"
    values:      
      type: "article"
      comments: "true"  