name: Sypalo.com
url: https://sypalo.com
type: website
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      show: "true"
  -
    scope:
      path: "en"
    values:
      lang: "en"
  -
    scope:
      path: "ru"
    values:
      lang: "ru"